Fixed HDFFV-11052 (CVE-2020-10812)
HDFGroup/hdf5 pull request #1017
Opened 2021-09-16 05:07 UTC by bmribler

Description
    The tool h5debug on a corrupted file produced a core dump.   The
    issue occurred during failure recovery when a null shared file pointer
    was being accessed.

    A permanent solution to handle corrupted file during failure recovery
    will require more careful consideration to avoid bad side-effects to
    other parts of the library.  In the meantime, a workaround is used to
    catch the attempt of accessing the null shared file pointer.  The tool
    will then return error instead of segfault.
Platforms tested:
    Linux/64 (jelly)

2021-09-16 05:09 UTC, bmribler commented on src/H5VLnative_file.c
I'm a bit confused about H5I_get_ref() and H5F_NREFS -> H5F_get_nrefs, please confirm that the use of these two functions here are correct.

2021-09-16 05:15 UTC, bmribler commented
After I applied the changes, the core dump was avoided but I got the infinite loop error:
HDF5: infinite loop closing library
L,T_top,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F,F

I created this draft PR so you can look over the changes and give me suggestions to eliminate the infinite loop error.  I think H5L_table_g was not 0 causing that but what can I do?

2021-09-16 15:59 UTC, gnuoyd commented
This change does not appear to fix the bug. How does `f->shared` unexpectedly become `NULL`?

2021-09-16 17:55 UTC, bmribler commented
> This change does not appear to fix the bug. How does `f->shared` unexpectedly become `NULL`?
The corrupted file caused wacky things to happen, Dave.  Dana helped me and I'm making changes to the ...changes.  As I mentioned in the Description, this is a temporary workaround that a few of us discussed and decided to present to other developers for more suggestions.

2021-09-16 18:25 UTC, gnuoyd requested changes
Root cause analysis should be performed.

2021-09-16 19:36 UTC, gnuoyd commented
It looks like the library tries to read a cache image from the file at byte offset 65792 when `h5debug` calls H5Fclose. The file is only 2565 bytes long, so the read fails. Here is the back trace:

```
bt
#0  H5F_block_read (f=f@entry=0x64a550, type=type@entry=H5FD_MEM_SUPER, 
    addr=65792, size=268435456, buf=0x7fffe6cdd010)
    at ../../../manydsets/src/H5Fio.c:147
#1  0x00007ffff785c2de in H5C__read_cache_image (cache_ptr=0x7ffff7f5e010, 
    f=0x64a550) at ../../../manydsets/src/H5Cimage.c:1083
#2  H5C__load_cache_image (f=0x64a550)
    at ../../../manydsets/src/H5Cimage.c:1083
#3  0x00007ffff785da14 in H5C__prep_image_for_file_close (f=0x64a550, 
    image_generated=image_generated@entry=0x7fffffffc21f)
    at ../../../manydsets/src/H5Cimage.c:1295
#4  0x00007ffff785026e in H5C_prep_for_file_close (f=f@entry=0x64a550)
    at ../../../manydsets/src/H5C.c:745
#5  0x00007ffff7837689 in H5AC_prep_for_file_close (f=f@entry=0x64a550)
    at ../../../manydsets/src/H5AC.c:1185
#6  0x00007ffff78ca3ab in H5F__dest (f=f@entry=0x64a550, 
    flush=flush@entry=true) at ../../../manydsets/src/H5Fint.c:1381
#7  0x00007ffff78ccc9f in H5F_try_close (f=0x64a550, 
    was_closed=was_closed@entry=0x0) at ../../../manydsets/src/H5Fint.c:2513
#8  0x00007ffff78ccf8c in H5F__close (f=f@entry=0x64a550)
    at ../../../manydsets/src/H5Fint.c:2315
#9  0x00007ffff7abe3bf in H5VL__native_file_close (file=0x64a550, 
    dxpl_id=<optimized out>, req=<optimized out>)
    at ../../../manydsets/src/H5VLnative_file.c:777
#10 0x00007ffff7aace8e in H5VL__file_close (cls=<optimized out>, req=0x0, 
    dxpl_id=792633534417207304, obj=<optimized out>)
    at ../../../manydsets/src/H5VLcallback.c:4115
#11 H5VL_file_close (vol_obj=vol_obj@entry=0x64c480, 
    dxpl_id=792633534417207304, req=0x0)
    at ../../../manydsets/src/H5VLcallback.c:4146
#12 0x00007ffff78ca096 in H5F__close_cb (file_vol_obj=0x64c480, 
    request=<optimized out>) at ../../../manydsets/src/H5Fint.c:216
#13 0x00007ffff793cf6a in H5I__dec_ref (request=0x0, 
    id=id@entry=72057594037927936) at ../../../manydsets/src/H5Iint.c:1036
#14 H5I__dec_app_ref (request=0x0, id=id@entry=72057594037927936)
    at ../../../manydsets/src/H5Iint.c:1108
#15 H5I_dec_app_ref (id=id@entry=72057594037927936)
    at ../../../manydsets/src/H5Iint.c:1156
#16 0x00007ffff78c0d79 in H5Fclose (file_id=file_id@entry=72057594037927936)
    at ../../../manydsets/src/H5F.c:1060
#17 0x0000000000401e3e in main (argc=<optimized out>, argv=<optimized out>)
    at ../../../../../manydsets/tools/src/misc/h5debug.c:820
(gdb) 
```

(Line numbers probably do not match `develop`.)

The error percolates up the stack to H5F__dest, which notes the error but does not return until after it sets `f->shared` to NULL at this line:

```
            f->shared = (H5F_shared_t *)H5FL_FREE(H5F_shared_t, f->shared);
```

At that point there is an extant ID for `f` but `f` is in a partially deinitialized state.

2021-09-16 21:57 UTC, derobins commented
In general, close routines shouldn't assume that the structures passed to them are in a sane state since they will be invoked after failed opens, etc. I haven't personally investigated this bug, but reworking the close call so it's more tolerant of NULL pointers and so that it tries to shut down as much as possible even in the face of badness seems to be what's needed here.

2021-09-27 18:42 UTC, bmribler commented
Dana will fix this instead.

2021-09-27 18:42 UTC, closed without merging