OESS-168: Remove clang warnings.
HDFGroup/hdf5 pull request #1072
Opened 2021-10-05 01:24 UTC by hyoklee

This patch will remove clang double-promotion warning.

2021-10-05 02:29 UTC, jhendersonHDF commented on test/dsets.c
> +    envval = HDgetenv("HDF5_DRIVER");
This was intentionally changed to be a macro and not a string so that all occurrences get updated if the env. variable name is ever changed.

2021-10-05 02:30 UTC, jhendersonHDF commented on test/dsets.c
> -                if (!driver_uses_modified_filename) {
These places intentionally check if the driver uses a modified filename so that they aren't run for certain VFDs.

2021-10-05 14:58 UTC, jhendersonHDF approved these changes

2021-10-06 01:27 UTC, lrknox approved these changes

2021-10-06 03:55 UTC, lrknox requested changes
2 DATASET TESTS (dsets) FAILED on Ubuntu with --enable-threadsafe --disable-hl options:
Testing     scaleoffset float with fill value, D-scaling (read)       *FAILED*
    Read different values than written.
    At index 0,2

Testing with new file format and non-paged aggregation
*FAILED*
HDF5-DIAG: Error detected in HDF5 (1.13.0-7) thread 1:
  #000: ../../src/H5F.c line 661 in H5Fcreate(): unable to synchronously create file
    major: File accessibility
    minor: Unable to create file
  #001: ../../src/H5F.c line 615 in H5F__create_api_common(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #002: ../../src/H5VLcallback.c line 3428 in H5VL_file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: ../../src/H5VLcallback.c line 3394 in H5VL__file_create(): file create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #004: ../../src/H5VLnative_file.c line 94 in H5VL__native_file_create(): unable to create file
    major: File accessibility
    minor: Unable to open file
  #005: ../../src/H5Fint.c line 1864 in H5F_open(): unable to truncate a file which is already open
    major: File accessibility
    minor: Unable to open file

2021-10-06 12:04 UTC, byrnHDF approved these changes

2021-10-14 19:17 UTC, lrknox approved these changes

2021-10-15 03:06 UTC, merged