Brings the post-open fix from LBNL
HDFGroup/hdf5 pull request #1096
Opened 2021-10-14 12:41 UTC by derobins

Brings the post-open fixes from https://github.com/hpc-io/hdf5/tree/post_open_fix

2021-10-14 14:50 UTC, qkoziol requested changes
Please talk to me before merging this code.

2021-10-15 12:53 UTC, byrnHDF commented on java/test/TestH5.java
> +import test.H5TestUtils;
Why is this imported into in every java file?
imports should only be in the file that uses that class.

2021-10-15 13:37 UTC, byrnHDF commented on java/src/jni/CMakeLists.txt
> +#SET_GLOBAL_VARIABLE (HDF5_LIBRARIES_TO_EXPORT "${HDF5_LIBRARIES_TO_EXPORT};${HDF5_JAVA_JNI_TEST_LIB_TARGET}")
Correct, this line can be deleted as the JNI_TEST library will not be installed.

2021-10-15 13:47 UTC, byrnHDF commented on java/test/CMakeLists.txt
> +file (WRITE ${PROJECT_BINARY_DIR}/Manifest.txt
to avoid possible conflicts it would be better to preface the Manifest.txt and indicate the Main-Class.

2021-10-15 13:54 UTC, byrnHDF commented on java/test/CMakeLists.txt
> +  add_dependencies (${HDF5_JAVA_TEST_LIB_TARGET}_${test_file} ${HDF5_JAVA_TEST_LIB_TARGET})
just one add_dependencies line.

2021-10-15 14:17 UTC, byrnHDF commented on src/H5Pdevelop.h
> +H5_DLL herr_t H5Pset_plugin_new_api_context(hid_t plist_id, hbool_t new_api_ctx);
APIs should be added to java.

2021-10-15 14:25 UTC, byrnHDF commented on test/test_usecases.sh.in
> +./swmr_check_compat_vfd
why?

2021-10-15 14:27 UTC, byrnHDF commented on test/testswmr.sh.in
> +./swmr_check_compat_vfd
testdir would be better then "."

2021-10-15 14:28 UTC, byrnHDF commented on test/testvdsswmr.sh.in
> +./swmr_check_compat_vfd
Why? Don't use just "." - it is not portable.

2021-10-15 14:36 UTC, byrnHDF commented on java/test/TestH5VL.java
> +    public void testH5VLfapl_is_native() throws Throwable {
Java should not test non-public APIs.

2021-10-15 14:44 UTC, byrnHDF commented on java/src/jni/h5jni_test.c
> + * Class:     test_H5TestUtils
What is the purpose of this?
Isn't the check within the public API?
Java doesn't call non-public APIs.

2021-10-15 15:19 UTC, byrnHDF commented on src/H5VLprivate.h
> +H5_DLL herr_t         H5VL_fapl_is_native(hid_t fapl_id, hbool_t *is_native);
Why isn't this function a public API?
There is a special program in utils, using it in testing to skip some tests. Wouldn't a user want to know that info if they are creating a "portable" application?

2021-10-19 13:10 UTC, byrnHDF commented on utils/CMakeLists.txt
> +set (H5_DEP_EXECUTABLES ${H5_DEP_EXECUTABLES} vds_elink_compat_vol)
Why is this being tagged for installation? The function would be more useful as a public API.

2021-10-20 13:22 UTC, epourmal commented on src/H5VLprivate.h
> +H5_DLL herr_t         H5VL_fapl_is_native(hid_t fapl_id, hbool_t *is_native);
Yes, this function should be public.

2021-11-02 22:59 UTC, derobins commented
NERSC is going to set up a PR of their own that incorporates the changes we've made here.

2021-11-02 22:59 UTC, closed without merging