Make it easier to find version specific docs.
HDFGroup/hdf5 pull request #1260
Opened 2021-12-03 00:56 UTC by gheber

Fixes #1249

2021-12-03 13:00 UTC, byrnHDF commented on configure.ac
> +  DOXYGEN_HTML_EXTRA_FILES='$(SRCDIR)/doxygen/hdf5_navtree_hacks.js $(SRCDIR)/doxygen/img/FF-IH_FileGroup.gif $(SRCDIR)/doxygen/img/FF-IH_FileObject.gif $(SRCDIR)/doxygen/img/FileFormatSpecChunkDiagr
Add to cmake file too.

2021-12-03 13:03 UTC, byrnHDF approved these changes

2021-12-03 13:25 UTC, byrnHDF approved these changes

2021-12-13 19:37 UTC, lrknox requested changes

2021-12-13 19:37 UTC, lrknox commented on doxygen/dox/Overview.dox
> +This documention includes specifications and documentation
```suggestion
This documentation includes specifications and documentation
```

2021-12-13 20:48 UTC, lrknox approved these changes

2021-12-13 21:13 UTC, merged