Bug setting variable named 0 to 1
HDFGroup/hdf5 pull request #1332
Opened 2022-01-03 23:12 UTC by hjmjohnson

2022-01-03 23:40 UTC, dzenanz approved these changes

2022-01-03 23:50 UTC, hjmjohnson commented
FYI:  Other cleanups to this file were found by the excellent VTK folks:  https://gitlab.kitware.com/third-party/hdf5/-/commit/90f7fd311f9311d5fdd432fec45b9cd2ec5c9beb

2022-01-11 19:33 UTC, byrnHDF requested changes
First this is against 1.12.1 which is a released version. Develop branch should be first choice for changes, as this branch will have the latest code. Second choice is the 1_12 branch to see if develop changes have been merged. Last choice would be a request for a patch release.

2022-01-12 13:50 UTC, byrnHDF commented
This has been fixed in the development branches.

2022-01-12 13:50 UTC, closed without merging