Addition of .pc file to autotools process
HDFGroup/hdf5 pull request #1420
Opened 2022-02-03 14:59 UTC by jkordani

I'm not sure this is complete yet, but I was having a hard time figuring out everything that the cmake process brings in to make the file.  Also, I'm not sure where to go so that this file is installed appropriately during make install

2022-02-03 15:11 UTC, byrnHDF commented
Check out the bin/h5cc.in file for consideration of variables.
Also, the bin/h5cc.in file includes the HL libraries.

A search on h5cc i the source should indicate installation commands, which could be used as a template.

2022-02-03 15:12 UTC, byrnHDF requested changes

2022-02-03 15:12 UTC, byrnHDF commented on config/hdf5.pc.in
> +Version: 1.13.1-1
This version should be a @var@ instead of hard-coded.

2022-03-16 13:14 UTC, byrnHDF commented on config/hdf5.pc.in
> +Version: 1.13.1-1
See src/libhdf5.settings.in for examples.

2023-06-07 21:11 UTC, derobins commented
There has been no movement on this in a long time. We'll attempt to add pkg-config support to the Autotools for 1.12.3 via a separate PR.

2023-06-07 21:11 UTC, closed without merging