CMake: respect GNUInstallDirs
HDFGroup/hdf5 pull request #1716
Opened 2022-05-03 02:34 UTC by thesamesam

This makes life a lot easier for in particular Linux distributions
as it means CMake will respect a standard set of arguments for
libdir, docdir, etc.

It also brings the CMake in line with autotools in terms of paths.

We've been using this downstream in Gentoo for quite some time
with no problems.

Signed-off-by: Sam James <sam@gentoo.org>

2022-05-03 15:50 UTC, byrnHDF commented
Need to determine how these changes will affect none linux platforms first.

2022-05-11 18:45 UTC, byrnHDF commented on c++/src/CMakeLists.txt
> +set (_PKG_CONFIG_LIBDIR \${exec_prefix}/${CMAKE_INSTALL_LIBDIR})
I like this change to use a variable instead of hard-coded dir names.

2022-05-11 18:45 UTC, byrnHDF commented on c++/src/CMakeLists.txt
> +set (_PKG_CONFIG_LIBDIR \${exec_prefix}/${CMAKE_INSTALL_LIBDIR})
I like this change to use a variable instead of hard-coded dir names.

2022-05-11 18:49 UTC, byrnHDF commented
Also will need a new configuration Release.txt entry.

2022-05-12 12:37 UTC, byrnHDF requested changes
The changes need to go into the HDFMacros file

2022-10-17 13:02 UTC, byrnHDF commented
Investigating again, because of history and not wanting to break other projects that rely on certain settings, I propose we add a build option "UseGNUInstallDirs" that calls the module and then sets the HDF5_INSTALL_* correctly.
This means changing all un-prefixed settings to use the appropriate HDF5_INSTALL_* variable.

2022-10-19 16:06 UTC, byrnHDF commented
See #2175 for reworked implementation - uses the option "HDF5_USE_GNU_DIRS". The option is OFF by default to not interfere with existing applications that depend on the installation dir structure.

2022-10-19 18:37 UTC, thesamesam commented
Fantastic -- I'd missed your earlier comments but I really appreciate you finishing this off! I'll close in favour of yours.

2022-10-19 18:37 UTC, closed without merging