Adds file locking documentation
HDFGroup/hdf5 pull request #2084
Opened 2022-09-04 11:33 UTC by derobins

This will eventually be rolled into the UG what that lands in develop

2022-09-06 20:13 UTC, lrknox commented on doc/file-locking.md
> +
It seems the condition above could satisfy those in lines 256 and 257.  What's the difference?

2022-09-07 16:19 UTC, hyoklee commented on doc/file-locking.md
> +  a shared lock. It's unclear why this was done and we'll look into removing
Shouldn't we remove code that we don't understand? This is a security hole.

2022-09-07 16:22 UTC, hyoklee commented on doc/file-locking.md
> +This API call can be used to override the configure defaults. It takes
How can an API override the configuration defaults?

2022-09-07 16:24 UTC, hyoklee commented on doc/file-locking.md
> +just need to be extra careful that you hold to rules for SWMR access.
Please explain what users should be extra caeful about.

2022-09-07 16:25 UTC, hyoklee commented on doc/file-locking.md
> +- WP = POSIX and Windows locks
Rewrite "Windows and POSIX locks" to match "WP"

2022-09-07 16:27 UTC, hyoklee commented on doc/file-locking.md
> +**Configure Option and Environment Variable**
I think title should be "Confgiure Option, H5P API, and Environment Variable"

2022-09-07 16:30 UTC, hyoklee commented on doc/file-locking.md
> +the lock callback of their underlying sub-files. The onion and MPI-IO VFDs do NOT
`onion` -> `Onion`

2022-09-07 16:36 UTC, hyoklee commented on doc/file-locking.md
> +the h5clear command-line tool, which is built with the library.
Add a `h5clear` example with a command line option. E.g.,

`h5clear -s file_lock_issue_file.h5`

2022-09-07 16:36 UTC, hyoklee requested changes
Please see my in-line comments.

2022-09-14 12:53 UTC, derobins commented
I'll address the comments when I get a little extra time.

2022-09-14 12:53 UTC, merged