CVE 2021 46242 develop
HDFGroup/hdf5 pull request #2255
Opened 2022-11-11 23:09 UTC by e4t

Fix two potential causes of usr-after-free:

- When evicting the superblock, NULL the corresponding entry
- When evicting driver info block, NULL the corresponding entry (CVE-2021-46242)

2022-11-11 23:12 UTC, e4t commented
This needs review by someone who is familiar with `H5F__super_read()`: I'm unsure whether `f->shared->sblock = NULL` is really needed. I've added a check whether it's value is the same as `sblock` as I cannot rule out, that it may have retained its previous value.

2022-11-12 03:06 UTC, hyoklee requested changes

2022-11-12 03:06 UTC, hyoklee commented on release_docs/RELEASE.txt
> +      whether the pointer is initialzed before using its value.
@e4t Please fix typo. Otherwise, this is amazingly good patch! Thank you!

2022-11-12 11:14 UTC, e4t commented on release_docs/RELEASE.txt
> +      whether the pointer is initialzed before using its value.
> @e4t Please fix typo. Otherwise, this is amazingly good patch! Thank you!

Thank you! Typo fixed.
I've rechecked the code, I'm now convinced that `f->shared->sblock` should be NULLed if expunged in the error path so I removed it. It seems there has been trouble with this before as the same function contains the code:
```
#if 1 /* bug fix test code -- tidy this up if all goes well */ /* JRM */
                    /* KLUGE ALERT!!                                                                               
                     *                                                                                             
                     * H5F__super_ext_write_msg() expects f->shared->sblock to                                     
                     * be set -- verify that it is NULL, and then set it.                                          
                     * Set it back to NULL when we are done.                                                       
                     */
                    HDassert(f->shared->sblock == NULL);
                    f->shared->sblock = sblock;
#endif /* JRM */
```
twice. Maybe the `HDassert(f->shared->sblock == NULL)` should be moved to the beginning of the function.

2022-11-12 18:44 UTC, hyoklee commented on release_docs/RELEASE.txt
> +      whether the pointer is initialzed before using its value.
Yes, this code is very complicated and requires a careful review. I really appreciate your effort to dig deep!

2022-12-02 04:21 UTC, jhendersonHDF approved these changes

2022-12-02 20:20 UTC, lrknox approved these changes

2022-12-02 20:23 UTC, lrknox commented
Test file POC1-H5AC_unpin_entry-useafterfree fails to open with error message h5dump error: unable to open file "POC1-H5AC_unpin_entry-useafterfree"

2022-12-02 20:24 UTC, merged