Apply szip LINK_COMP_LIBS CmakeFilters.cmake patch from msys2
HDFGroup/hdf5 pull request #2409
Opened 2023-01-18 09:19 UTC by mkitti

Originally by @Biswa96

See
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-hdf5/hdf5-fix-find-szip.patch

2023-01-18 13:34 UTC, byrnHDF approved these changes

2023-01-18 13:40 UTC, Biswa96 commented
Warning: A valid patch in msys2 may not mean it can be applied upstream. Please check if the change is compatible with the expected behavior in all use cases.

Also, I guess that the condition in the patch would be better if it was written like this `if (ZLIB_FOUND) ... else() ... endif()`.

2023-01-18 13:41 UTC, byrnHDF commented on CMakeFilters.cmake
> +        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${ZLIB_LIBRARIES})
This line should just be added to the if block that is next. (line 67)

2023-01-18 14:04 UTC, byrnHDF requested changes
Looking further at this, there is another problem - once pass this section and ignoring the External build section, there is another set LINK_COMP_LIBS command.

2023-01-18 14:10 UTC, byrnHDF commented on CMakeFilters.cmake
> +        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${ZLIB_LIBRARIES})
Look at line 94.  I think this set (LINK_COMP_LIBS line should replace the one at line 94 as that is the end of any ZLIB_FOUND checking and ZLIB_LIBRARIES is set correctly no matter which path was taken.

2023-02-17 22:23 UTC, byrnHDF commented
I will incorporate this into a new PR that will add FetchContent options that was implemented in hdf4 CMake.

2023-02-17 22:23 UTC, closed without merging

2023-03-07 21:56 UTC, mkitti commented
I believe this was fixed by https://github.com/HDFGroup/hdf5/pull/2492