Fix issue with collective metadata writes of global heap data
HDFGroup/hdf5 pull request #2480
Opened 2023-02-16 20:42 UTC by jhendersonHDF

Fixes #2433

2023-02-16 21:49 UTC, brtnfld approved these changes
LGTM, I verified that it fixes the NetCDF failures 🔧.

2023-02-17 16:27 UTC, qkoziol requested changes
lgtm, but should have a new regression test also

2023-02-17 17:37 UTC, jhendersonHDF commented
> lgtm, but should have a new regression test also

I agree we need a reproducer, though it might be difficult to come up with one. Any idea how a parallel netCDF program is causing a write of global heap metadata? My only initial thought was reference and/or VL types, but we don't support access to the global heap in parallel.

2023-02-17 17:47 UTC, qkoziol commented
VL or ref datatype in an attribute?

2023-02-17 18:05 UTC, jhendersonHDF commented
> VL or ref datatype in an attribute?

Ah ok.. I suppose that wouldn't really be problematic parallel access since all ranks would be doing the same thing.

2023-02-20 14:13 UTC, qkoziol approved these changes
Great!

2023-02-20 14:49 UTC, lrknox approved these changes

2023-02-20 14:49 UTC, merged

2023-02-26 21:13 UTC, wkliao commented on release_docs/RELEASE.txt
> +    - Fixed an issue with collective metadata writes of global heap data
Shouldn't this statement be under "Bug Fixes since HDF5-1.14.0 release", instead of 1.13.3?