Addressed various Doxygen grammar issues.
HDFGroup/hdf5 pull request #2524
Opened 2023-03-09 17:42 UTC by brtnfld

Doxygen Doc. Changes.

2023-03-09 18:20 UTC, byrnHDF approved these changes

2023-03-11 19:11 UTC, lrknox requested changes

2023-03-11 19:11 UTC, lrknox commented on src/H5Cpkg.h
> + * This operation is complicated by the fact that entries other the
```suggestion
 * This operation is complicated by the fact that entries other than the
```

2023-03-11 19:11 UTC, lrknox commented on src/H5Lpublic.h
> + *          encoding is  specified in \p lcpl_id rather than that of the
```suggestion
 *          encoding is specified in \p lcpl_id rather than in that of the
```

2023-03-11 19:11 UTC, lrknox commented on src/H5MF.c
> +         *           be stored in the free space managers super block
```suggestion
         *           be stored in the free space manager's superblock
```

2023-03-11 19:11 UTC, lrknox commented on src/H5Opublic.h
> + *          file that points to that object. See the “Programming Model”
I think this should be 'point':  it's the hard links that point, not the file.

2023-03-11 19:11 UTC, lrknox commented on src/H5Spublic.h
> + *       does not have or needs to write data.
I don't know the rule for this, but the subject is process and the verbs with number agreement are does have or does need.  I don't think process does not needs is correct.

2023-03-11 19:11 UTC, lrknox commented on src/H5Tenum.c
> + * Purpose:	Finds the symbol name that corresponds the specified
```suggestion
 * Purpose:	Finds the symbol name that corresponds to the specified
```

2023-03-11 19:11 UTC, lrknox commented on src/H5Tenum.c
> + * Purpose:	Finds the value that corresponds the specified symbol
```suggestion
 * Purpose:	Finds the value that corresponds to the specified symbol
```

2023-03-11 19:11 UTC, lrknox commented on src/H5Tpublic.h
> + *        a newly committed datatype
Judging from only this sentence, it seems that a committed datatype that did not yet exist will be created.  If true, I think new is better.   I also think that after it's created, newly-committed makes sense in **both** lines 1161 and 1164.  Seeing newly in line 1238, though, the whole process being described should be considered.

2023-03-13 15:13 UTC, brtnfld commented on src/H5Tpublic.h
> + *        a newly committed datatype
fixed

2023-03-13 15:17 UTC, brtnfld commented on src/H5Spublic.h
> + *       does not have or needs to write data.
fixed.

2023-03-13 15:25 UTC, lrknox approved these changes

2023-03-13 16:53 UTC, merged