Minor cherry-pick merges to 1.12
HDFGroup/hdf5 pull request #2581
Opened 2023-03-17 21:04 UTC by lrknox

2023-03-17 21:06 UTC, lrknox commented
I made this a draft for now, because I want develop tests to run before merging to 1.12

2023-03-20 14:04 UTC, byrnHDF commented on tools/test/h5dump/testh5dump.sh.in
> +<<<<<<< HEAD
Conflict markers!

2023-03-20 14:04 UTC, byrnHDF requested changes
Conflict markers in testh5dump.sh.in need clean up.

2023-03-20 14:34 UTC, lrknox commented
Conflict resolved and references to onion vfd and test files removed.

2023-03-20 14:35 UTC, lrknox commented on tools/test/h5dump/testh5dump.sh.in
> +<<<<<<< HEAD
fixed.

2023-03-29 17:12 UTC, byrnHDF approved these changes

2023-03-29 18:15 UTC, merged