Avoid suppressing error output for non-tentative file opens
HDFGroup/hdf5 pull request #2632
Opened 2023-03-24 21:17 UTC by jhendersonHDF

2023-03-25 01:24 UTC, qkoziol requested changes
The goal is good here, but the changes here and code in the existing next 'if' block should be integrated into one coherent set of code, instead of overlapping / duplicating code.

2023-03-25 04:46 UTC, jhendersonHDF commented
@qkoziol Does that look a little better? I'm not super fond of the organization but it was the only way I could think of since we can't really conditionally use H5E_BEGIN/END_TRY without duplicating code.

2023-03-26 14:58 UTC, qkoziol approved these changes
This reads better and the code is clearer now, thanks for tuning it up!

2023-03-31 14:35 UTC, lrknox approved these changes

2023-04-01 03:36 UTC, merged