CMake: Let runtime checks through stdout only
HDFGroup/hdf5 pull request #2666
Opened 2023-04-05 16:59 UTC by jschueller

This avoids mixing emulators errors to configure results while cross-compiling with wine.

2023-04-05 17:06 UTC, byrnHDF requested changes
RUN_OUTPUT_STDOUT_VARIABLE isn't available until CMake 3.25, our minimum is 3.18.

2023-04-05 17:19 UTC, jschueller commented
ok, lets use it depending on CMAKE_VERSION

2023-04-05 17:48 UTC, byrnHDF approved these changes

2023-04-11 19:27 UTC, lrknox approved these changes

2023-04-11 19:28 UTC, merged