Check for invalid AAPL in H5Aopen
HDFGroup/hdf5 pull request #2712
Opened 2023-04-13 04:42 UTC by jhendersonHDF

The AAPL isn't used in H5Aopen, but the VOL tests check for failure when passing an invalid AAPL and the library doesn't currently check the AAPL for serial builds. It only gets checked in a roundabout way for parallel builds in H5CX_set_apl when collective metadata reads aren't enabled globally for the file.

2023-04-13 05:05 UTC, jhendersonHDF commented
@byrnHDF Does the failure in Java for MSVC here look like another case of a dependency issue when running the tests in parallel?

2023-04-13 18:15 UTC, derobins commented
A quick test for this would be helpful to ensure it doesn't regress.

2023-04-13 18:19 UTC, qkoziol requested changes

2023-04-13 18:19 UTC, qkoziol commented on src/H5VLnative_attr.c
> +    if (NULL == (plist = (H5P_genplist_t *)H5I_object_verify(aapl_id, H5I_GENPROP_LST)))
H5P_object_verify would be a better (stronger) check.

2023-04-13 19:06 UTC, jhendersonHDF commented
> 

How do we want to handle the duplicated test between adding one here and the existing one in the VOL tests?

2023-04-13 20:57 UTC, jhendersonHDF commented
@qkoziol pushed those changes. Once this PR is merged I have a GitHub action for the VOL tests hopefully ready to go that regression tests this. It should fix a single failure on Ubuntu.

2023-04-14 21:40 UTC, mattjala approved these changes

2023-04-17 20:22 UTC, derobins approved these changes

2023-04-17 20:22 UTC, merged