Add h5copy help test and verify consistency
HDFGroup/hdf5 pull request #2902
Opened 2023-05-05 14:11 UTC by byrnHDF

2023-05-05 16:52 UTC, derobins commented
No Autotools test?

2023-05-07 06:12 UTC, gyoju approved these changes

2023-05-08 16:06 UTC, derobins requested changes
Needs an Autotools test

2023-05-09 16:06 UTC, hyoklee approved these changes

2023-05-16 20:14 UTC, jhendersonHDF approved these changes

2023-05-17 15:40 UTC, lrknox commented
Autotools tests have been added to address requested changes.

2023-05-17 15:41 UTC, merged