Update H5private.h to fix errors with vastprintf() and astprintf()
HDFGroup/hdf5 pull request #2955
Opened 2023-05-14 04:47 UTC by cross85

When building hd5f with intel compilers on ubuntu 22.04, I got the following error message:

`
H5E.c:1339:9: error: call to undeclared function 'vasprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    if (HDvasprintf(&tmp, fmt, ap) < 0)
        ^
./H5private.h:1498:34: note: expanded from macro 'HDvasprintf'
#define HDvasprintf(RET, FMT, A) vasprintf(RET, FMT, A)
                                 ^
H5E.c:1339:9: note: did you mean 'vsprintf'?
./H5private.h:1498:34: note: expanded from macro 'HDvasprintf'
#define HDvasprintf(RET, FMT, A) vasprintf(RET, FMT, A)
                                 ^
/usr/include/stdio.h:373:12: note: 'vsprintf' declared here
extern int vsprintf (char *__restrict __s, const char *__restrict __format,
           ^
1 error generated.
`

This error message is fixed adding `#define _GNU_SOURCE` to [H5private.h](https://github.com/HDFGroup/hdf5/commit/0228a16b26049108f8c9165362fcad0e755ca24d)

2023-05-15 03:20 UTC, derobins requested changes
This needs to be a change to the Autotools and CMake, not the header file.

2023-05-15 03:20 UTC, derobins commented
Which OS and compiler is this?

2023-05-15 04:51 UTC, cross85 commented
I used the autotools, and I think the latest Intel version (2023.1.0)

2023-05-15 12:47 UTC, byrnHDF commented
> I used the autotools, and I think the latest Intel version (2023.1.0)

classic compilers or the newer ifx?
Our instance of 22.04 and Intel compilers do not show this error for the new compiler.

2023-05-15 14:14 UTC, cross85 commented
I used the new ifx compileres with hdf5 1.14.1-2

2023-05-26 13:31 UTC, derobins commented
Can you create an issue for this and close this PR? I want to track this as we implement oneAPI testing, but this fix is incorrect and can't go into the library.

2023-05-26 17:55 UTC, cross85 commented
> Can you create an issue for this and close this PR? I want to track this as we implement oneAPI testing, but this fix is incorrect and can't go into the library.

It's the new compilers problem, I used oneAPI with icc and ifort instead of icx and ifx, and works ok.

2023-05-26 21:52 UTC, derobins commented
> > Can you create an issue for this and close this PR? I want to track this as we implement oneAPI testing, but this fix is incorrect and can't go into the library.
> 
> It's the new compilers problem, I used oneAPI with icc and ifort instead of icx and ifx, and works ok.

Okay, but we don't see it in our testing and this fix breaks other compilers, so it couldn't go in even if it were the right fix.

2023-06-06 19:19 UTC, derobins commented
I'm going to go ahead and close this since this change can't go into the library. A proper fix should go in the Autotools and CMake files. In the meantime, it'd be useful to create an issue for this.

2023-06-06 19:19 UTC, closed without merging