Added plugin registration info to docs
HDFGroup/hdf5 pull request #2985
Opened 2023-05-19 15:36 UTC by gheber

Doesn't this belong here rather than in some obscure place in Confluence?

2023-05-19 15:43 UTC, byrnHDF approved these changes

2023-05-19 16:29 UTC, jhendersonHDF commented on doc/registered_filters.md
> +| WARNING: be aware that compression filters require that the library not use `H5_MEMORY_ALLOC_SANITY_CHECK`.  Building in debug mode automatically enables this feature in earlier releases, which cau
I wonder if this should say "current versions" of HDF5 rather than "future versions"

2023-05-19 18:26 UTC, hyoklee requested changes
Please remove single quotes inside table. There are many places to remove them.

2023-05-19 18:26 UTC, hyoklee commented on doc/registered_filters.md
> +| LZF | 32000 | **LZF lossless compression used by H5Py project** The LZF filter is an alternative DEFLATE-style compressor for HDF5 datasets, using the free LZF library by Marc Alexander Lehmann. It
[`h5py`](http://h5py.org) -> [h5py](http://h5py.org)

2023-05-22 12:52 UTC, gheber commented
This document must be synchronized with https://github.com/HDFGroup/hdf5_plugins/blob/master/docs/PluginLibraries.txt, and there should be only one authoritative copy in one place.

2023-06-16 14:50 UTC, bmribler commented on doc/registered_filters.md
> +Please contact the maintainer of a filter for help with the plugin.
Should the contact here be "HDF Help Desk" too?

2023-06-16 14:59 UTC, bmribler commented on doc/registered_filters.md
> +| Filter | ID  | Description | URL | Contact |
Is there a reason for duplicating the contents of https://portal.hdfgroup.org/display/support/Filters here?  Using the link will ensure the information stay up-to-date when any filter is added/removed/updated.

2023-10-08 01:18 UTC, derobins commented
This should be moved to https://github.com/HDFGroup/hdf5_plugins

Recommend we close

2023-10-13 16:34 UTC, closed without merging