Track s3 i/o when S3COMMS_DEBUG enabled
HDFGroup/hdf5 pull request #3139
Opened 2023-06-15 20:08 UTC by mattjala

@ajelenak mentioned this would be useful as a general feature.

2023-06-15 20:13 UTC, byrnHDF commented
Don't we already have a "Developer" options - maybe even just enabling the <package>_DEBUG settings?

2023-06-15 20:35 UTC, hyoklee approved these changes

2023-06-15 22:25 UTC, derobins commented
> Don't we already have a "Developer" options - maybe even just enabling the _DEBUG settings?

The DEBUG options here turn on logging / printf dumps, not extra checks, like in the library. We should probably rename the symbol to _LOGGING or similar.

2023-06-15 22:27 UTC, derobins commented on src/H5FDs3comms.c
> +              len);
This needs to use PRIuHADDR for haddr_t values and zu for size_t

2023-06-15 22:29 UTC, derobins requested changes
Can go in when the format string is changed

2023-06-16 12:37 UTC, byrnHDF commented
Oh, this is a pre-existing define, too bad, the name, S3COMMS_TRACE, would be a closer to what it does.

2023-06-16 12:37 UTC, byrnHDF approved these changes

2023-06-16 16:04 UTC, derobins approved these changes

2023-06-16 16:04 UTC, merged