Add note about HDF5_VOL_CONNECTOR to h5dump usage
HDFGroup/hdf5 pull request #3159
Opened 2023-06-19 22:38 UTC by mattjala

This clarifies that it defaults to using the VOL specified by the environment variable, as discussed in #2645.

2023-06-20 12:31 UTC, byrnHDF commented
This will need the testfiles fixed to add these lines to the help output.

2023-06-20 14:21 UTC, byrnHDF commented
There are multiple testfiles due to expected failure tests. Testing should expose the files.

2023-06-20 15:14 UTC, byrnHDF approved these changes

2023-06-20 23:48 UTC, derobins approved these changes

2023-06-20 23:51 UTC, derobins requested changes
I would change the text to say " or the native VOL connector if that is not set." Otherwise, people might become confused when the environment variable is not set. Also, this documentation should be extended to all the command-line tools that take a VOL parameter.

2023-06-21 19:34 UTC, glennsong09 approved these changes

2023-06-28 14:14 UTC, hyoklee approved these changes

2023-06-28 16:56 UTC, derobins approved these changes

2023-06-28 16:56 UTC, merged