Remove prohibition against building Universal Binaries on macOS
HDFGroup/hdf5 pull request #318
Opened 2021-02-07 19:47 UTC by seanm

2021-02-07 19:48 UTC, seanm commented
@epourmal

2021-02-07 19:54 UTC, byrnHDF approved these changes

2021-02-07 20:31 UTC, lrknox approved these changes

2021-02-07 20:35 UTC, seanm commented
Ideally this would be backported to earlier branches too.  Personally, I use 1.10.x and would most like to see it there (and newer).

2021-02-07 20:48 UTC, seanm commented
@imikejackson

2021-02-07 20:55 UTC, byrnHDF commented
Should there be a RELEASE.txt entry?

2021-02-07 20:58 UTC, byrnHDF reviewed
Also, is the user expected to know how to build a universal binary and when not to?

2021-02-07 21:01 UTC, seanm commented
> Also, is the user expected to know how to build a universal binary and when not to?

Depending on who you mean by "user", then yes, any Mac programmer building HDF5 would know when/if he wants to build universal.  Now that Apple is selling both Intel and ARM Macs, the 'when' is usually "always".

2021-02-08 14:17 UTC, imikejackson commented
For what it's worth I'm ok with these changes.

I also wouldn't mind seeing this back ported to the 1.10.x branch as that is what we are using in our projects.

2021-02-08 14:24 UTC, byrnHDF requested changes
I think we do need to have a release note entry about this.
Just something simple that dates the change and why.

2021-02-08 14:41 UTC, qkoziol approved these changes

2021-02-08 15:21 UTC, byrnHDF commented
Once the change is in develop, I can make the merges to 1.12 and 1.10.
Allen

2021-02-08 15:32 UTC, seanm commented
OK, I'll amend this with a note in the release notes...

2021-02-08 17:17 UTC, seanm commented
Where should the note go?  In RELEASE.txt?

2021-02-08 17:55 UTC, byrnHDF commented
Correct, newest at top of section Configuration. I would use the "New Features"  Configuration section rather then the "Bug Fixes".

2021-02-08 18:37 UTC, byrnHDF commented on release_docs/RELEASE.txt
> +
One more line - initials and date, please.

2021-02-08 19:14 UTC, byrnHDF approved these changes

2021-02-08 20:16 UTC, merged