Fixed HDFFV-11150
HDFGroup/hdf5 pull request #356
Opened 2021-02-18 21:04 UTC by bmribler

Description
    Replaced an HDassert with a check for null pointer in H5O_dec_rc() to
    catch null pointer in corrupted data situation.
    As a result, removed the null check prior to H5O_dec_rc() calls.
Platforms tested:
    Linux/64 (jelly)

2021-02-18 21:06 UTC, bmribler commented
Regarding test, the user (Mathworks) hasn't provided the corrupted file yet, and I wasn't able to generate one that would cause the stated segfault.

2021-02-19 03:15 UTC, qkoziol commented
I still don't understand how the assert could get triggered with the original code.   If chk_proxy->oh is NULL, H5O__dec_rc should never be called and therefore the assert won't be executed / checked.   If chk_proxy->oh is non-NULL, H5O__dec_rc will get called, oh will be non-NULL and the assert shouldn't be triggered.

I agree with your assessment that it is impossible to generate a file that will cause the segfault. ;-)

2021-02-19 03:16 UTC, qkoziol requested changes
Doesn't look like the code as originally written could trigger the type of bug described, so there must be some other cause for the bug.

2021-02-19 16:59 UTC, bmribler commented
Actually, the segfault was before the check for chk_proxy->oh being NULL was added.  The assert caused a crash at another place.  So instead of adding another check to the other place and, I think, yet another place, I thought it would be better to change H5O__dec_rc() instead.  I discussed that with you via email in December.

2021-02-19 17:10 UTC, qkoziol commented
> Actually, the segfault was before the check for chk_proxy->oh being NULL was added. The assert caused a crash at another place. So instead of adding another check to the other place and, I think, yet another place, I thought it would be better to change H5O__dec_rc() instead. I discussed that with you via email in December.

Ah, OK, that explains it! :-)  I think it's harmless to commit then, but would really be better if there was a reproducer for triggering it.

2021-02-19 17:10 UTC, qkoziol approved these changes

2021-02-19 17:20 UTC, bmribler commented
I was messing around with a file for that but got distracted.  If I ever get it, I'll add the test.  Thank you!

2021-02-19 19:01 UTC, lrknox approved these changes

2021-02-19 19:01 UTC, merged