Add AOCC GitHub Action (#3504)
HDFGroup/hdf5 pull request #3657
Opened 2023-10-11 03:13 UTC by hyoklee

close #3504

Note: HDF5 Fortran doesn't work with this action. Enabling it will fail the action.

2023-10-11 16:35 UTC, derobins approved these changes

2023-10-11 16:36 UTC, derobins commented
> close #3504
> 
> Note: HDF5 Fortran doesn't work with this action. Enabling it will fail the action.

Why does Fortran fail?

2023-10-11 17:21 UTC, hyoklee commented
> > close #3504
> > Note: HDF5 Fortran doesn't work with this action. Enabling it will fail the action.
> 
> Why does Fortran fail?

```
  FCLD     libhdf5_fortran.la
clang-16: error: unknown argument: '-soname'
clang-16: error: no such file or directory: 'libhdf5_fortran.so.1000'
```

2023-10-11 20:02 UTC, bmribler approved these changes

2023-10-13 16:33 UTC, derobins commented on .github/workflows/linux-auto-aocc-ompi.yml
> +  push:
Needs to also be on PR

2023-10-13 16:34 UTC, derobins requested changes
Should also be on PR

2023-10-14 05:49 UTC, derobins commented
I have a fix for AOCC w/ shared/Fortran/parallel. Let's get that in and then modify this PR to build + test more stuff.

2023-10-14 20:51 UTC, derobins approved these changes

2023-10-14 20:52 UTC, merged