Add Intel oneAPI/MPI and LLVM for Windows Action.
HDFGroup/hdf5 pull request #3661
Opened 2023-10-12 01:37 UTC by hyoklee

This simple action may help Windows users (e.g., #3275 user).

 This action is also good for 1.14.3 release testing as well,
 since it uses the latest CMake 3.27.7 and Intel oneAPI for Windows.
 However, only 49% tests passed, while 1124 out of 2199 tests failed.

2023-10-12 12:31 UTC, byrnHDF commented
Why is this not added to the intel-cmake.yml file?

2023-10-12 12:32 UTC, byrnHDF requested changes
Integrate into intel-cmake.yml file

2023-10-12 12:33 UTC, byrnHDF commented
Also why is CMake 3.27.7 mentioned - the minimum for hdf5 is 3.18.

2023-10-12 15:43 UTC, hyoklee commented
> Also why is CMake 3.27.7 mentioned - the minimum for hdf5 is 3.18.

Spack is at 3.27.7.

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/cmake/package.py

2023-10-12 15:44 UTC, hyoklee commented
> Why is this not added to the intel-cmake.yml file?

I want to have a separate badge. E.g., 

https://github.com/hyoklee/hdf5/blob/develop/WATCHME.md

2023-10-12 17:43 UTC, byrnHDF commented
We will need to do badges differently, Every callable workflow can return a status all the way back up the stack. One solution might be to use a json file.
Another possibility: https://github.com/marketplace/actions/dynamic-badges

Workflows need to be kept consistent.

2023-10-13 16:38 UTC, derobins commented on .github/workflows/win-ninja-icx.yml
> +  push:
Should also be PR

2023-10-23 14:23 UTC, byrnHDF commented on tools/test/h5dump/CMakeTests.cmake
> +    #HDFTEST_COPY_FILE("${PROJECT_SOURCE_DIR}/expected/tfloatsattrs.wddl" "${PROJECT_BINARY_DIR}/testfiles/std/tfloatsattrs.ddl" "h5dump_std_files")
This change should not be changed in an action - this would need to be a different PR.

2023-10-23 14:24 UTC, byrnHDF requested changes
This is not a solution

2023-11-10 15:14 UTC, closed without merging

2023-11-10 15:14 UTC, byrnHDF commented
Resolved by #3836