Fix H5Pset_evict_on_close failing with non MPI-IO use
HDFGroup/hdf5 pull request #3752
Opened 2023-10-23 02:28 UTC by glennsong09

Adds in a check to see if the the MPIO FD is being used and if the MPI size is greater than one before failing.

2023-10-23 04:37 UTC, derobins commented on src/H5Pfapl.c
> +    if (H5Pget_driver(fapl_id) == H5FD_MPIO) {
You can't make public API calls in internal functions

2023-10-23 04:47 UTC, derobins commented on src/H5Pfapl.c
> +    int             mpi_size;            /* MPI size */
These should be protected with H5_HAVE_PARALLEL ifdefs

2023-10-23 04:50 UTC, derobins commented on src/H5Pfapl.c
>  #endif /* H5_HAVE_PARALLEL */
If your intent is to allow setting this property when mpi_size is 1, you aren't setting it when the checks succeed.

2023-10-23 04:51 UTC, derobins requested changes
Needs changes (see comments - should be easy to fix)

2023-10-23 22:31 UTC, jhendersonHDF commented
@glennsong09 and I discussed these changes and have a different approach to fixing the issue

2023-10-24 04:02 UTC, derobins commented
> @glennsong09 and I discussed these changes and have a different approach to fixing the issue

Do we need to close this, then?

2023-10-24 04:03 UTC, jhendersonHDF commented
Closing this PR in favor of changes coming in a different PR

2023-10-24 04:03 UTC, closed without merging