Don't build util tests when HDF5_EXTERNALLY_CONFIGURED=ON
HDFGroup/hdf5 pull request #3781
Opened 2023-10-26 09:55 UTC by Krzmbrzl

Fixes #3780

2023-10-26 09:56 UTC, Krzmbrzl commented on utils/CMakeLists.txt
>  endif ()
I think one could also think of only building the tests if the utils are built in the first place. Building only the tests doesn't seem to make much sense :thinking: :eyes:

2023-10-26 13:33 UTC, byrnHDF requested changes
We should guard all the add_subdirectory test folders, not just an arbitrary instance.

2023-10-26 14:32 UTC, Krzmbrzl commented
I think I added guards for all other tests as well :eyes:

2023-10-26 14:41 UTC, byrnHDF approved these changes

2023-10-30 16:20 UTC, lrknox approved these changes

2023-10-30 16:21 UTC, jhendersonHDF approved these changes

2023-10-30 16:22 UTC, brtnfld approved these changes

2023-10-30 17:47 UTC, merged