Complete the `if command line option` sentence.
HDFGroup/hdf5 pull request #3868
Opened 2023-11-22 16:44 UTC by hyoklee

Make comment clear and consistent.

From:
```
   /* enable error reporting if command line option */
```

To:
```
  /* Enable error reporting if -E command line option is specified */
```

2023-11-22 17:12 UTC, byrnHDF requested changes

2023-11-22 17:12 UTC, byrnHDF commented on tools/src/h5dump/h5dump.c
> +    /* Enable error reporting if -E command line option is specified */
While technically correct, we are discouraging the use of the short names. Use "--enable-error-stack"

2023-11-22 21:25 UTC, byrnHDF approved these changes

2023-11-22 21:39 UTC, bmribler approved these changes

2023-11-24 12:19 UTC, lrknox approved these changes

2023-11-24 12:19 UTC, merged