Add Doxygen documentation for H5FD module and h5tools.
HDFGroup/hdf5 pull request #3909
Opened 2023-12-23 03:26 UTC by hyoklee

This will help tool users by exposing h5dump VFD options.

![20231222_h5tools_doxygen](https://github.com/HDFGroup/hdf5/assets/4994401/af90822e-9d40-4928-bbb9-bbf933be91e0)

![20231222_h5tools_doxygen_drivernames](https://github.com/HDFGroup/hdf5/assets/4994401/13b12321-7813-4ee3-9255-9e15d177182a)

Once this PR is merged, add the link to https://portal.hdfgroup.org/documentation/hdf5-docs/registered_virtual_file_drivers_vfds.html for #3878.

P.S. H5FD was missing so I added it as well.

2023-12-26 13:48 UTC, byrnHDF requested changes
This basically exposes the tools API, which we have avoided because of a lack of design and resources. This "publish the API" needs a company directive.
 In addition this adds a "C" source file to the doxygen. Also, we should not add just the C library APIs for FD package without the adding the other languages.

2023-12-26 13:57 UTC, lrknox commented
> This basically exposes the tools API, which we have avoided because of a lack of design and resources. This "publish the API" needs a company directive. 
@derobins What do you think?

2024-01-02 20:51 UTC, jhendersonHDF commented
I think we definitely need something like this, but also think it should just be a table in the H5FD module file doxygen. I don't think it makes sense to tie it to the tools, especially since these changes are just exposing an implementation detail.

2024-01-21 22:43 UTC, derobins commented
We should expose the names, but not in this way. I'm going to go ahead and close this.

@hyoklee - Please create an issue for this and add it to the 1.14.4 milestone.

2024-01-21 22:43 UTC, closed without merging