Add clarification for current behavior of H5Get_objtype_by_idx()
HDFGroup/hdf5 pull request #4120
Opened 2024-03-12 18:51 UTC by glennsong09

It seems to be an unintentional change, but the current behavior is not documented anywhere. 

Addresses #1917.

2024-03-12 21:21 UTC, bmribler approved these changes

2024-03-14 14:09 UTC, derobins commented
Documenting the change in behavior is great, but we shouldn't close the issue until we understand why the change occurred and whether we're happy with the current behavior.

2024-03-14 15:46 UTC, jhendersonHDF commented
> Documenting the change in behavior is great, but we shouldn't close the issue until we understand why the change occurred and whether we're happy with the current behavior.

Bisected to https://github.com/HDFGroup/hdf5/commit/ca1b9025fe8be1eab6bd76d58ab78bb9450c41f1

2024-03-14 16:05 UTC, glennsong09 commented
> Documenting the change in behavior is great, but we shouldn't close the issue until we understand why the change occurred and whether we're happy with the current behavior.

If I delete the line in my PR, does it stop it from automatically closing the issue?

2024-03-14 16:07 UTC, jhendersonHDF commented
> > Documenting the change in behavior is great, but we shouldn't close the issue until we understand why the change occurred and whether we're happy with the current behavior.
> 
> If I delete the line in my PR, does it stop it from automatically closing the issue?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

"Addresses" isn't one of GitHub's keywords, so this PR shouldn't close the issue when it's merged. You can also look in the Development section in the bottom right to see if the issue is linked to the PR.

2024-03-18 19:51 UTC, mattjala commented on src/H5Gpublic.h
> + * \note    As of 1.12.0, H5Get_objtype_by_idx() returns the type of the object
Typo: `H5Get_objtype_by_idx` -> `H5Gget_objtype_by_idx`

2024-03-18 19:52 UTC, mattjala requested changes
Looks good besides the typo

2024-03-19 18:12 UTC, glennsong09 commented on src/H5Gpublic.h
> + * \note    As of 1.12.0, H5Get_objtype_by_idx() returns the type of the object
Fixed.

2024-03-20 23:00 UTC, jhendersonHDF approved these changes

2024-03-22 16:15 UTC, mattjala approved these changes

2024-03-22 16:16 UTC, merged