Release asset tarballs with no version filenames
HDFGroup/hdf5 pull request #4494
Opened 2024-05-15 21:56 UTC by brtnfld

This should allow other CI and documentation to point to 

https://github.com/HDFGroup/hdf5/releases/latest/download/hdf5.tar.gz

to get the latest source release and to avoid complicated "one-liners" when trying to find the name of the versioned tarballs.

2024-05-15 21:57 UTC, brtnfld commented
It does not create assets when I release from my fork, so I have not checked if it works. Do you have any ideas on how I can get that to work?

2024-05-16 12:49 UTC, byrnHDF commented
Do we want this everytime daily-build runs or only under release-build?

2024-05-16 14:01 UTC, brtnfld commented
Just for a release build.

2024-05-16 14:21 UTC, byrnHDF commented on .github/workflows/tarball.yml
> +          cp ${{ inputs.use_tag }}.tar.gz hdf5.tar.gz
These should be moved to the two new steps below (line 166/169)

2024-05-16 14:22 UTC, byrnHDF commented on .github/workflows/tarball.yml
> +      - name: Save tgz-tarball_nover
These two new steps should be conditioned with:
        if: ${{ (inputs.use_environ == 'release') }}

2024-05-16 14:25 UTC, byrnHDF commented on .github/workflows/release-files.yml
> +          sha256sum hdf5.tar.gz >> hdf5.sha256sums.txt
The files need a step to download the artifacts
then a separate step to add the sha.
All conditioned on:
        if: ${{ (inputs.use_environ == 'release') }}

2024-05-16 14:26 UTC, byrnHDF commented on .github/workflows/release-files.yml
> +              hdf5.tar.gz
These should not be here - not release environ

2024-05-16 14:26 UTC, byrnHDF requested changes
Requires adding conditional steps.

2024-05-16 15:48 UTC, byrnHDF commented on .github/workflows/release-files.yml
> +#              name: cp-to-non-versioned
The artifact names here must match the artifact names uploaded.  Then the files will be available for the sha256sum.

2024-05-16 15:51 UTC, byrnHDF commented on .github/workflows/tarball.yml
> +          cp ${{ inputs.use_tag }}.tar.gz hdf5.tar.gz
With the next step these can be removed from this step

2024-05-16 15:52 UTC, byrnHDF commented on .github/workflows/tarball.yml
> +              name: tgz-tarball_nover
This is the artifact name to be used in the release-files download steps.

2024-05-16 18:05 UTC, byrnHDF approved these changes

2024-05-17 13:26 UTC, merged