Allow HDF5_LIB_INFIX to work with DLL
HDFGroup/hdf5 pull request #4500
Opened 2024-05-17 16:15 UTC by byrnHDF

2024-05-21 18:58 UTC, derobins requested changes
The naming scheme here would change the names from the previous behavior.

Also, the description field of any non-trivial PR should be filled in so people can more easily interpret the changes.

2024-05-28 12:33 UTC, lrknox commented
> The naming scheme here would change the names from the previous behavior.
> 
> Also, the description field of any non-trivial PR should be filled in so people can more easily interpret the changes.

These have been addressed

2024-05-28 12:35 UTC, lrknox approved these changes

2024-05-28 15:26 UTC, derobins approved these changes

2024-05-28 15:27 UTC, derobins approved these changes

2024-05-28 15:27 UTC, merged