Fix VOL CI CMake builds
HDFGroup/hdf5 pull request #4654
Opened 2024-07-16 14:58 UTC by mattjala

VOL CI started failing after  #4613 due to CMake build error:

```
CMake Error at src/CMakeLists.txt:1205 (get_target_property):
  get_target_property() called with non-existent target
  "/usr/lib/x86_64-linux-gnu/libz.so".
```

4613 added the `get_target_property()` invocation in order to populate `_PKG_CONFIG_LIBS_PRIVATE` with library's output names instead of the names used to refer to them in `${LINK_COMP_LIBS}`.

This adds a check that the target exists to CMake. If it doesn't exist, it defaults to the old library string instead of the output name; I'm not entirely certain what the ramifications of this are, or what the overall goals of the original change were. 

This PR also changes the VOL CI to be run against the current HDF branch instead of HDFGroup/develop so that other repos can detect if their changes break CI. This shouldn't change anything about the daily VOL connector CI, since that is run on develop anyway.

2024-07-16 15:07 UTC, byrnHDF commented on src/CMakeLists.txt
> +if(TARGET ${libs})
While this is a workaround - it is not the solution for the root problem.
The actual problem is that the CMake FindZLIB.cmake module does not set an OUTPUT_NAME on the target it creates, which is the second problem. The first problem is that the variable returned in ZLIB_LIBRARIES is not a target.

There will be a proper PR soon.

2024-07-16 15:07 UTC, byrnHDF requested changes
remove the changes to src/CMakeLists.txt

2024-07-16 17:54 UTC, byrnHDF approved these changes

2024-07-17 16:48 UTC, lrknox approved these changes

2024-07-17 16:57 UTC, merged