Add bounds checking to avoid heap-based buffer overflow vulnerability
HDFGroup/hdf5 pull request #4785
Opened 2024-08-29 06:45 UTC by wswsmao

fix CVE-2022-26061
https://talosintelligence.com/vulnerability_reports/TALOS-2022-1487

2024-08-29 13:37 UTC, hyoklee approved these changes

2024-08-29 15:59 UTC, derobins commented
Do you have a test file? There's no test to ensure this is really fixed.

2024-08-30 01:45 UTC, wswsmao commented
> Do you have a test file? There's no test to ensure this is really fixed.

Ok，I will add test files as appendix

2024-10-01 16:18 UTC, mattjala requested changes
Needs a test file for regression testing

2024-10-22 00:16 UTC, derobins commented
We've removed the gif tools from the HDF5 library, so I'm going to close this.

2024-10-22 00:16 UTC, closed without merging

2025-12-23 22:42 UTC, fortnern commented
For posterity: there is a test (gif) file in the linked TALOS report, in the form of hex editor output:

```
00000000: 4749 4638 396c 0a00 0300 020d 188e b9fd  GIF89l..........
00000010: 616c 0e00 2c00 0003 0005 0005 0000 0041  al..,..........A
00000020: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000030: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000040: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000050: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000060: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000070: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000080: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
00000090: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000a0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000b0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000c0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000d0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000e0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
000000f0: 4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
```