Skip unseekable file test on Cygwin
HDFGroup/hdf5 pull request #4803
Opened 2024-09-04 17:12 UTC by mattjala

Different implementation of hdf5#4797. Ideally the root issue will be fixed eventually, but for now we should avoid a known segfault during testing.

The metadata cache assertion that triggers an error in debug builds hasn't been converted to a regular error because it uses a debug-build-exclusive routine.

2024-09-04 17:13 UTC, hyoklee approved these changes

2024-09-04 17:52 UTC, qkoziol requested changes
Please don't put OS/system-specific #ifdefs in.

2024-09-04 18:36 UTC, mattjala commented on test/h5test.c
> +    if ((fp = fopen("/cygdrive", "r")) != NULL) {
A perverse user could define this drive on a non-Cygwin system, but I'm not aware of any other way to check that Cygwin is in use besides the `__CYGWIN__` directive.

2024-09-04 19:05 UTC, qkoziol requested changes
This is fundamentally no different than an #ifdef on the OS/system name.  Like #ifdefs, this will quickly become mysterious and forgotten, disabled forever.

2024-09-04 19:52 UTC, derobins commented
I'm not a fan of papering over failing tests. We should try to understand and fix the underlying issue.

2024-09-06 15:29 UTC, mattjala commented
Closing this, since the root issue should be fixed instead. Details in #4804

2024-09-06 15:29 UTC, closed without merging