Draw attention to 3rd step in process to update so numbers for release.
HDFGroup/hdf5 pull request #4825
Opened 2024-09-12 20:17 UTC by lrknox

resetting LT_VERS_AGE was missed for the last release.   The 3rd step instruction is now clearly separated from the second step instruction and the steps are numbered.  A step describing the update is also added to the RELEASE_PROCESS.md file.

2024-09-12 20:33 UTC, byrnHDF approved these changes

2024-09-13 15:02 UTC, hyoklee requested changes
Drop `lists` from email address.

2024-09-13 15:02 UTC, hyoklee commented on release_docs/RELEASE_PROCESS.md
> +6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@lists.hdfgroup.org.
hdf5lib@hdfgroup.org

2024-09-13 15:51 UTC, lrknox commented on release_docs/RELEASE_PROCESS.md
> +6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@lists.hdfgroup.org.
6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@lhdfgroup.org.
```suggestion
6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@lists.hdfgroup.org.
```

2024-09-13 15:52 UTC, lrknox commented on release_docs/RELEASE_PROCESS.md
> +6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@lists.hdfgroup.org.
```suggestion
6. Verify release branches for third-party software used: SZIP, ZLIB, and Plugins; and announce release versions to hdf5lib@hdfgroup.org.
```

2024-09-13 16:03 UTC, mattjala approved these changes

2024-09-13 16:21 UTC, hyoklee approved these changes

2024-09-13 16:49 UTC, merged