Sync develop changes 9/11 - 9/13 to hdf5_1_14
HDFGroup/hdf5 pull request #4833
Opened 2024-09-13 21:34 UTC by lrknox

2024-09-13 21:36 UTC, byrnHDF commented on config/cmake/FindHDFS.cmake
> +             RESULT_VARIABLE_VALUE Hadoop_RETURN)
Should not be changed - "VALUE" is incorrect

2024-09-13 21:53 UTC, byrnHDF approved these changes

2024-09-13 22:08 UTC, derobins commented on release_docs/RELEASE.txt
> +
This should not have been merged to 1.14. --enable-threads and HDF5_ENABLE_THREADS should be develop-only.

2024-09-13 22:09 UTC, derobins requested changes
Need to remove the comment about --enable-threads (and check to make sure that was not merged)

2024-09-14 03:38 UTC, lrknox commented
> Need to remove the comment about --enable-threads (and check to make sure that was not merged)

Release note about --enable-threads has been removed.

2024-09-16 12:46 UTC, byrnHDF approved these changes

2024-09-16 17:17 UTC, derobins approved these changes

2024-09-16 17:18 UTC, merged