Renamed DEFAULT_API_VERSION to HDF5_DEFAULT_API_VERSION in CMake
HDFGroup/hdf5 pull request #4982
Opened 2024-10-19 07:18 UTC by derobins

All other HDF5 library CMake options are prefixed with HDF5_

2024-10-19 07:19 UTC, derobins commented
I did not bother to update the versions to 2.0, etc. since that should be done in a separate PR

2024-10-19 23:17 UTC, qkoziol approved these changes

2024-10-20 03:20 UTC, bmribler approved these changes

2024-10-21 12:44 UTC, byrnHDF requested changes
DEFAULT_API_VERSION has at least 43 references in code that needs updated.

2024-10-21 13:18 UTC, mattjala approved these changes

2024-10-21 13:30 UTC, byrnHDF commented
Superceded by #4990

2024-10-21 15:35 UTC, closed without merging