Prefix remaining CMake options except for CMake BUILD* variables
HDFGroup/hdf5 pull request #4990
Opened 2024-10-21 13:28 UTC by byrnHDF

Renamed remaining HDF5 library CMake options except for CMake BUILD* variables
    
      DEFAULT_API_VERSION to HDF5_DEFAULT_API_VERSION
      DISABLE_PDB_FILES to HDF5_DISABLE_PDB_FILES
      ONLY_SHARED_LIBS to HDF5_ONLY_SHARED_LIBS
      ALLOW_UNSUPPORTED to HDF5_ALLOW_UNSUPPORTED
      TEST_SHELL_SCRIPTS to HDF5_TEST_SHELL_SCRIPTS

      All other HDF5 library CMake options are prefixed with HDF5_

2024-10-21 13:29 UTC, byrnHDF commented
Closes #4982

2024-10-21 15:31 UTC, derobins approved these changes

2024-10-21 15:32 UTC, derobins commented on src/H5build_settings.autotools.c.in
> +    "    With deprecated public symbols:HDF5_DEFAULT_API_VERSIONS@\n"
The Autotools symblol needs to stay the same

2024-10-21 15:32 UTC, derobins commented on src/libhdf5.settings.autotools.in
> +    With deprecated public symbols:HDF5_DEFAULT_API_VERSIONS@
Also needs to be reverted

2024-10-21 15:33 UTC, derobins requested changes
Need to revert Autotools files

2024-10-22 12:49 UTC, byrnHDF commented
> Need to revert Autotools files

Completed

2024-10-22 22:40 UTC, derobins approved these changes

2024-10-22 22:40 UTC, merged