Add unicode doc to doxygen Tech Notes
HDFGroup/hdf5 pull request #5136
Opened 2024-11-20 22:51 UTC by byrnHDF

2024-11-21 03:12 UTC, hyoklee requested changes

2024-11-21 03:12 UTC, hyoklee commented on doxygen/dox/TechnicalNotes.dox
> +through the object’sH5L_info_t structure which can be obtained using #H5Lvisit or #H5Lget_info_by_idx calls.
`object’sH5L_info_t` -> `object's H5L_info_t`

2024-11-21 14:37 UTC, hyoklee commented on doxygen/dox/TechnicalNotes.dox
> +HDF5 uses characters in object names (which are actually link names, but that’s a story for a
Can we replace `’` with `'`?

2024-11-21 14:37 UTC, hyoklee commented on doxygen/dox/TechnicalNotes.dox
> +predictable ways. There is an apparent consensus in the Linux community that “UTF-8 is just the right way to go.”
Can we replace `“ ”` with plain `""`?

2024-11-21 14:43 UTC, hyoklee reviewed
Please minimize the use of 8-bit characters in code documentation.

2024-11-21 16:52 UTC, byrnHDF commented
> Please minimize the use of 8-bit characters in code documentation.

These are all conversions from html/md files and it can be difficult to catch everything - appreciate the checks everyone does!

2024-11-21 17:04 UTC, hyoklee approved these changes

2024-11-22 14:38 UTC, lrknox approved these changes

2024-11-22 14:39 UTC, merged