Add check for broken links in Doxygen generated html docs
HDFGroup/hdf5 pull request #5138
Opened 2024-11-21 18:40 UTC by hyoklee

This PR will report 36 broken links.  
CI will fail until they are all fixed.

close #4928

2024-11-21 19:11 UTC, byrnHDF requested changes
Add link check workflow

2024-11-21 19:11 UTC, byrnHDF commented on .github/workflows/main-cmake.yml
I think this would be better served by a dedicated workflow that just needs to configure and build on one platform then having it check on all the systems.  After all the links don't change between platforms.

2024-11-21 19:14 UTC, byrnHDF commented on .github/workflows/main-cmake.yml
Also nothing in CMake tests finished because the Macs claim to not know about the command.

2024-11-21 19:26 UTC, byrnHDF commented
You could use the first 65 lines of the netcdf.yml file for the configure and build and then add the link check.

2024-11-21 20:08 UTC, byrnHDF approved these changes, later dismissed

2024-11-21 20:12 UTC, byrnHDF commented
Could you add one more thing - put the actual linkcheck into a separate step
      - name: check
        run: |
          mkdir build
          cd build
          cmake -DHDF5_BUILD_DOC:BOOL=ON ..
          make doxygen
          cd hdf5lib_docs/html
          linkchecker --check-extern ./index.html

Change to:
      - name: create
        run: |
          mkdir build
          cd build
          cmake -DHDF5_BUILD_DOC:BOOL=ON ..
          make doxygen

     - name: check
        run: |
          cd build/hdf5lib_docs/html
          linkchecker --check-extern ./index.html

2024-11-27 13:47 UTC, byrnHDF commented
We should get this in now, to keep track of issues. The remaining errors are in files that will be converted to doxygen and will fix the URLs.
After the merge we will temporarily add a continue after error to allow PR merges to pass. This will be reverted once the remaining files are converted.

2024-11-27 13:47 UTC, byrnHDF approved these changes

2024-11-27 13:48 UTC, lrknox approved these changes

2024-11-27 13:49 UTC, merged