Split doxygen pages from spec and TN into files
HDFGroup/hdf5 pull request #5165
Opened 2024-12-03 14:30 UTC by byrnHDF

Improves maintenance of pages involved.

2024-12-03 17:42 UTC, mattjala commented on doxygen/dox/AppDbgging.dox
> +\subsection subsec_adddbg_intro_trace API Tracing
API Tracing was removed in #4341

2024-12-03 17:49 UTC, mattjala commented on doxygen/dox/TableSpec.dox
> +documentation.) This document is an additional specification do define a standard profile
`do define` -> `to define`

2024-12-03 17:57 UTC, mattjala commented on doxygen/dox/Unicode.dox
> +<b>Windows</b> systems use a different Unicode encoding, UCS-2 (discussed in this UTF-16 article) at
No article linked here. Probably supposed to link to https://en.wikipedia.org/wiki/UTF-16

2024-12-03 18:13 UTC, mattjala commented on doxygen/dox/VFLTechNote.dox
> +Mappings predefined in the 'H5FDpublic.h' file are:
These are defined in `H5FDdevelop.h` at present

2024-12-03 18:14 UTC, mattjala commented on doxygen/dox/VFLTechNote.dox
> +<td>The read function reads data from file file beginning at address addr and continuing
`file file` -> `file`

2024-12-03 18:17 UTC, mattjala requested changes
A few typos and out of date info

2024-12-03 19:29 UTC, byrnHDF commented
> A few typos and out of date info

Updated

2024-12-12 20:55 UTC, mattjala approved these changes, later dismissed

2024-12-12 21:53 UTC, lrknox submitted a review, later dismissed

2024-12-12 23:39 UTC, lrknox approved these changes

2024-12-13 14:33 UTC, mattjala approved these changes

2024-12-13 16:31 UTC, merged