Prevent H5Pset_vol from changing default VOL
HDFGroup/hdf5 pull request #5172
Opened 2024-12-09 22:06 UTC by mattjala

This prevents the connector in `H5VL_def_conn_s` and the one used by `H5P_DEFAULT/H5P_FILE_ACCESS_DEFAULT` from diverging.

2024-12-10 00:24 UTC, qkoziol requested changes
In principal, yes, but rejecting the default property list of each type should apply to *all* the 'set' routines, for all types of property lists.

And, you don't need to reject H5P_DEFAULT, since H5P_object_verify() will already fail for that value.

2024-12-10 00:28 UTC, qkoziol commented
I suggest that you put the appropriate checking inside H5P_object_verify()

2024-12-10 00:30 UTC, jhendersonHDF commented
> In principal, yes, but rejecting the default property list of each type should apply to _all_ the 'set' routines, for all types of property lists.

In this case I'd call it a "not letting perfect be the enemy of good enough" situation. I asked Matt to create this PR due to the issue I encountered specifically with changing the VOL on the default FAPL. Fixing all the cases (and testing them) would be a decently larger effort.

> And, you don't need to reject H5P_DEFAULT, since H5P_object_verify() will already fail for that value.

I'd actually prefer to explicitly reject `H5P_DEFAULT` and `H5P_FILE_ACCESS_DEFAULT` first as an invalid argument check and not rely on `H5P_object_verify()` doing that, in case someone updates it in the future to accept `H5P_DEFAULT` and another parameter to allow it to translate to the correct property list.

2024-12-10 03:15 UTC, qkoziol commented
I understand your perspective, but I think the problem should be easy to address in a few hours of work:  add a new 'is_lib_default' flag to the property list structure, which is only set to true for the actual default property lists, and is set to false when one of those property lists is copied.

Then add a parameter to H5P_object_verify(), or someplace else that's central to the 'set' calls, that indicates that H5P_object_verify() is being called from a 'set' routine.   Then fail in H5P_object_verify() when both are true.

Probably only ~50 lines of actual code.  (and 600 lines of trivial changes to calls to H5P_object_verify :-)

2024-12-11 15:19 UTC, qkoziol commented on src/H5Pfapl.c
> +    if (H5P_is_default_plist(plist_id))
This shouldn't be necessary now.

2024-12-11 15:53 UTC, qkoziol commented on test/plists.c
This test looks fine, but there's already a property list test (src/gen_plist.c).

2024-12-11 15:55 UTC, qkoziol reviewed
Please merge the new and old tests together, so there's only one property list test.

Otherwise, looks good - thanks for taking the time to implement a holistic approach that addresses the problem at its root.

2024-12-11 15:55 UTC, qkoziol commented on test/plists.c
(It doesn't matter to me which name you choose)

2024-12-11 21:16 UTC, mattjala commented on test/plists.c
`gen_plists` is associated with test files and is only built when a specific argument is provided. I think it makes sense to isolate that from "regular" property list tests.

2024-12-11 21:42 UTC, qkoziol commented on test/plists.c
Apologies, I had the wrong name, that should have been: test/tgenprop.c

2024-12-11 23:02 UTC, qkoziol approved these changes

2024-12-16 16:08 UTC, lrknox approved these changes

2024-12-17 13:52 UTC, merged